# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9358963f767657876576dd1e30b37273880cd2dc8ee1a6b06d3ffed76a1ed33bf07ae85084436fa53b524f909725b46f942faaf794bfc600bb73c444ba412ca0

test:
  secret_key_base: 778d3cf5b31c85a77cb40207be1fbcd42e1a39358f4d531c848be54ba8d5d25277412b056d0d042908aea2c08e9274b26a51dc8905b7a64c8c0d628665aa121a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
